image: registry.gitlab.com/yungyuc/turgon:latest

before_script:
  - which g++; g++ --version
  - which python3; python3 --version

build:
  script:
  - cd ${CI_PROJECT_DIR}/solver
  - mkdir build ; cd build
  - cmake -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/solver ..
  - make install VERBOSE=${VERBOSITY:-0}
  - cd ${CI_PROJECT_DIR}/writing
  - make VERBOSE=${VERBOSITY:-0}
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/writing/*.pdf
    - ${CI_PROJECT_DIR}/writing/log/
