image: registry.gitlab.com/yungyuc/turgon:latest

before_script:
- which python; python --version

pdf_build:
  script:
  - cd ${CI_PROJECT_DIR}/writing
  - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - ${CI_PROJECT_DIR}/writing/*.pdf
    - ${CI_PROJECT_DIR}/writing/log/
    expire_in: 1 week
