image: registry.gitlab.com/yungyuc/turgon:latest

before_script:
  - which g++; g++ --version
  - which python3; python3 --version
  - sudo bash ${CI_PROJECT_DIR}/contrib/depend/install.sh pybind11
  - sudo bash ${CI_PROJECT_DIR}/contrib/depend/install.sh xtl
  - sudo bash ${CI_PROJECT_DIR}/contrib/depend/install.sh xsimd
  - sudo bash ${CI_PROJECT_DIR}/contrib/depend/install.sh xtensor
  - sudo bash ${CI_PROJECT_DIR}/contrib/depend/install.sh xtensor-python

build:
  script:
  - cd ${CI_PROJECT_DIR}/spacetime
  - mkdir -p build ; cd build
  - cmake
    -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/spacetime
    -DCMAKE_BUILD_TYPE=Release
    ..
  - make install VERBOSE=${VERBOSITY:-0}
  - cd ${CI_PROJECT_DIR}/spacetime
  - nosetests3 -v tests/*
  - cd ${CI_PROJECT_DIR}/writing
  - make VERBOSE=${VERBOSITY:-0}
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/writing/*.pdf
    - ${CI_PROJECT_DIR}/writing/log/
